# Generated by Django 3.1.3 on 2022-09-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='submission',
            name='enrollment',
            field=models.ManyToManyField(to='onlinecourse.Enrollment'),
        ),
    ]
